sonar.projectKey=NHSDigital_hometest-service
sonar.organization=nhsdigital
sonar.projectName=hometest-service

sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8

sonar.sources=lambdas,ui

sonar.tests=lambdas/src,ui/src,tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.spec.js,**/*.test.tsx,**/*.spec.tsx,**/*.test.jsx,**/*.spec.jsx

sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/dist/**,\
  **/build/**,\
  **/.next/**,\
  **/.swc/**,\
  **/public/**,\
  **/test-results/**,\
  **/*.md,\
  ui/content/content.json,\
  lambdas/scripts/**,\
  lambdas/jest/**,\
  lambdas/goose-migrator-lambda/src/main.go

sonar.typescript.tsconfigPaths=lambdas/tsconfig.json,ui/tsconfig.json,tests/tsconfig.json
sonar.javascript.environments=node,browser
sonar.javascript.lcov.reportPaths=lambdas/coverage/lcov.info,ui/coverage/lcov.info

# Duplication - ignore test files
sonar.cpd.exclusions=**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.spec.js,**/*.test.tsx,**/*.spec.tsx,**/*.test.jsx,**/*.spec.jsx

# New code definition
sonar.newCode.referenceBranch=main
