---
services:
  localstack:
    image: localstack/localstack:4.14.0
    container_name: localstack-main
    profiles:
      - backend
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=lambda,iam,logs,s3,cloudformation,sts,apigateway,ssm,secretsmanager,sqs,events
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  ui:
    image: node:24
    container_name: ui
    profiles:
      - frontend
    working_dir: /app
    volumes:
      - ../ui:/app
      - ui_node_modules:/app/node_modules
    env_file:
      - ../ui/.env.local
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run dev"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localstack:4566

  postgres-db:
    image: postgres:17.9
    container_name: postgres-db
    profiles:
      - backend
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=local_hometest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d local_hometest_db"]
      interval: 2s
      timeout: 5s
      retries: 10

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    profiles:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: ["--verbose"]

volumes:
  ui_node_modules:
  postgres_data:
