-- +goose Up

/*
    =================================================================
    STATIC DATA

    This is for data that will not change between local and PoC env
    =================================================================
 */

INSERT INTO status_type (status_code, description)
VALUES
('GENERATED', 'Order has been generated by the order service'),
('QUEUED', 'Order has been queued for processing'),
('PLACED', 'Order has been placed with the supplier'),
('ORDER_RECEIVED', 'Order has been confirmed by the supplier'),
('DISPATCHED', 'Test has been dispatched to the patient'),
('RECEIVED', 'Test has been received by the laboratory'),
('COMPLETE', 'Test results are ready from the supplier')
ON CONFLICT DO NOTHING;

INSERT INTO result_type (result_code, description)
VALUES
('RESULT_AVAILABLE', 'Test results are available from the supplier'),
('RESULT_WITHHELD', 'Test result are being withheld by the supplier for any reason')
ON CONFLICT DO NOTHING;


-- +goose Down
DELETE FROM status_type
WHERE status_code = 'GENERATED';
DELETE FROM status_type
WHERE status_code = 'QUEUED';
DELETE FROM status_type
WHERE status_code = 'PLACED';
DELETE FROM status_type
WHERE status_code = 'ORDER_RECEIVED';
DELETE FROM status_type
WHERE status_code = 'DISPATCHED';
DELETE FROM status_type
WHERE status_code = 'RECEIVED';
DELETE FROM status_type
WHERE status_code = 'COMPLETE';
DELETE FROM result_type
WHERE result_code = 'RESULT_AVAILABLE';
DELETE FROM result_type
WHERE result_code = 'RESULT_WITHHELD';
