---
name: "Test stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string

permissions:
  actions: read
  checks: write
  contents: write
  pull-requests: write

jobs:
  test-unit-ui:
    name: "UI unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: Initialize mise
        uses: ./.github/actions/init-mise
      - name: "Run UI tests"
        uses: ./.github/actions/run-npm-tests
        with:
          working-directory: ui
          nodejs-version: "${{ inputs.nodejs_version }}"
          artifact-prefix: ui
          test-name: "Jest UI Tests"
          coverage-threshold: "70"
          report-title: "UI Coverage Report"

  test-unit-lambda:
    name: "Lambda unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: Initialize mise
        uses: ./.github/actions/init-mise
      - name: "Run Lambda tests"
        uses: ./.github/actions/run-npm-tests
        with:
          working-directory: lambdas
          nodejs-version: "${{ inputs.nodejs_version }}"
          artifact-prefix: lambdas
          test-name: "Jest Lambda Tests"
          report-title: "Lambdas Coverage Report"

  test-goose-migrations:
    name: "Test Goose DB Migrations"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Initialize mise"
        uses: ./.github/actions/init-mise
      - name: "Run Goose Migration Tests"
        run: mise run test-migrations

  perform-static-analysis:
    name: "Perform static analysis"
    needs: [test-unit-ui, test-unit-lambda, test-goose-migrations]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Full history is needed to improving relevancy of reporting
      - name: "Download UI coverage data"
        uses: actions/download-artifact@v8
        with:
          name: ui-coverage-data
          path: ui/coverage/

      - name: "Download Lambda coverage data"
        uses: actions/download-artifact@v8
        with:
          name: lambdas-coverage-data
          path: lambdas/coverage/
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
